name: Homework CI

on:
  push:
    branches:
      - main

# Kell a GitHub Container Registry-hez (ghcr.io)
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build with Maven wrapper
        run: ./mvnw clean package


  docker_build_and_publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and publish Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.actor }}/cubix/1/homework/app:springboot
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME


  verify_image:
    needs: docker_build_and_publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Make verify script executable
        run: chmod +x verify-image.sh

      - name: Run verify script
        run: ./verify-image.sh
