name: Homework CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build with Maven wrapper
        run: ./mvnw clean package


  docker_build_and_publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u papaslev --password-stdin

      - name: Build and publish Docker image
        run: |
          docker build -t ghcr.io/papaslev/cubix-first-homework:latest .
          docker push ghcr.io/papaslev/cubix-first-homework:latest


  verify_image:
    needs: docker_build_and_publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x verify-image.sh

      - name: Verify the image
        run: ./verify-image.sh
